# https://metallb.universe.tf/configuration/

apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: sample
  namespace: metallb
spec:
  myASN: 64500
  peerASN: 64501
  peerAddress: 192.168.99.1
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.51.240-192.168.51.250
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: example
  namespace: metallb
spec:
  ipAddressPools:
  - first-pool
---
apiVersion: metallb.io/v1beta1
kind: BFDProfile
metadata:
  name: testbfdprofile
  namespace: metallb
spec:
  receiveInterval: 380
  transmitInterval: 270